(function(){
'use strict';
const EN={
  "guide": "Guide",
  "harvest_moon_festival": "GAME001TOKEN",
  "dailies_orders": "Dailies and Orders",
  "crops": "GAME068TOKEN Crops",
  "preparations": "Gathering Preparations",
  "gathering": "Gathering",
  "unlocks": "Unlocks",
  "event_center": "Event Center",
  "activate_event": "Activate Event",
  "event_active": "Event Active",
  "enable_event_recipes": "Enable Event Recipes in Production",
  "reserved_farmlands": "Reserved GAME046TOKEN",
  "permanent_unlocks_tracked": "permanent unlocks tracked",
  "moonray_wheat_coins_total": "GAME004TOKEN total",
  "event_progress_title": "GAME026TOKEN Progress",
  "event_progress_intro": "GAME026TOKEN Points are the main progress of the event. They are awarded from spent GAME004TOKEN, produced crops and recipes, and decorations bought. Crop and recipe production gives very little progress compared with what the event requires.",
  "event_best_source": "Best current point source: buy GAME049TOKEN (gold) tier decorations.",
  "points_per_coin": "points / coin",
  "purchase_limit_48": "Purchase limit: 48",
  "purchase_limit_12": "Purchase limit: 12",
  "guide_step_all": "Buy every event decoration at least once for GAME072TOKEN progress and the event completion bonus.",
  "guide_step_market": "Buy GAME032TOKEN until GAME071TOKEN unlocks.",
  "guide_step_laurel": "Buy GAME071TOKEN until GAME056TOKEN unlocks.",
  "guide_step_flicker": "Then buy GAME066TOKEN. Its unlock recipe is called GAME054TOKEN, while the GAME014TOKEN item is called GAME066TOKEN.",
  "guide_step_osmanthus": "Once Osmanthus Rain unlocks, you can buy it or GAME066TOKEN, as both have the same value.",
  "flicker_osmanthus": "GAME066TOKEN/Osmanthus Rain",
  "limit_reached": "Reached the purchase limit?",
  "limit_reset": "Go to the GAME036TOKEN, open the second tab, and sell the decorations back for Bud Tickets. This resets the purchase limit.",
  "furniture_path": "GAME014TOKEN: GAME072TOKEN (9) → GAME029TOKEN → GAME042TOKEN → choose an item → GAME014TOKEN",
  "recommended_event_farmlands": "Recommended Event GAME046TOKEN:",
  "two_farms_enough": "Two reserved GAME046TOKEN are more than enough to supply event orders and event dailies.",
  "permanent_unlock_tracking": "Permanent Unlock Tracking:",
  "moonray_wheat_coins": "GAME004TOKEN",
  "production_optional": "Production recipes are optional:",
  "production_optional_text": "their GAME050TOKEN advantage is only a few percent at best, so GAME004TOKEN are normally more valuable for event progression and rewards first.",
  "crop_mutations": "GAME068TOKEN Crop Mutations",
  "crop_intro": "Mutation results are random. Higher RV progression and the GAME002TOKEN unlock more mutation types and later improve mutation odds.",
  "default": "Default",
  "giant_default": "GAME075TOKEN mutation is available immediately.",
  "module_l1": "Module Lv. 1",
  "module_l2": "Module Lv. 2",
  "module_l3": "Module Lv. 3",
  "module_l4": "Module Lv. 4",
  "colorful_unlock": "GAME057TOKEN unlocks.",
  "shining_unlock": "GAME069TOKEN unlocks.",
  "crystalline_unlock": "GAME038TOKEN unlocks.",
  "mutation_odds_up": "All mutation types get increased odds.",
  "mutation_advice": "If you are specifically farming mutations, postpone hard focus until at least RV 12 unless your GAME026TOKEN Points progression is already finished.",
  "mutated_dismantle": "Mutated event crops can be dismantled for GAME018TOKEN.",
  "mutated_exchange": "GAME018TOKEN can be used to buy mutated crops, including event mutations. Mutated Event crops can also be exchanged / gifted to a friend.",
  "mutation_collection": "Mutation GAME042TOKEN",
  "click_crop": "Click a crop image to mark it acquired.",
  "quantity": "Quantity",
  "complete": "Complete",
  "completed": "Completed",
  "daily_task": "Daily task",
  "event_orders": "Event Orders",
  "orders_no_currency": "Add GAME026TOKEN orders here. Completion tracking does not grant currency.",
  "search_event_recipe": "Search event recipe…",
  "add_event_order": "Add event order",
  "no_event_orders": "No active GAME026TOKEN orders.",
  "dailies": "Dailies",
  "dailies_no_currency": "Completion tracking only. These buttons do not grant currency.",
  "restart_dailies": "Restart Dailies",
  "recipe_note": "Recipe Note",
  "unlocked": "Unlocked",
  "tracked_used": "Tracked Used",
  "still_needed": "Still Needed",
  "all_unlocks": "All Permanent Unlocks",
  "recipes": "Recipes",
  "decorations": "Decorations",
  "click_box": "Click anywhere on a box to toggle the permanent unlock.",
  "gathering_preparations": "Gathering Preparations",
  "harvest_gathering": "Harvest Gathering",
  "unlock_oct6": "Unlocks on October 6, 2026",
  "unlock_oct20": "Unlocks on October 20, 2026",
  "event_recipe_warning": "Event recipes are not used by default because their GAME050TOKEN value is only a small improvement and GAME004TOKEN are normally better spent on event progression. Purchasable event recipes must also be marked as unlocked in the Event Center → Unlocks tab. Enable them anyway?",
  "event_recipe_warning_title": "Enable event recipes?",
  "enable_anyway": "Enable anyway",
  "keep_disabled": "Keep disabled",
  "personality_any": "Personality Any",
  "rec_personality": "Rec Personality",
  "trait": "Trait",
  "needed": "Needed",
  "family_required": "Family Aniimo required",
  "any_matching_aniimo": "Any matching Aniimo can cover this job.",
  "evolution_tree": "Evolution Tree",
  "obtained_from": "Obtained From",
  "homeland_traits": "Homeland Traits",
  "translation_note_title": "Translation note",
  "translation_note_body": "Official game names use Aniimo’s own localization where available. Aniiland’s Site Language text is machine translated, so some wording may be inaccurate.",
  "translation_help": "If you want to help improve your language, please contact Wintira on Reddit or Discord.",
  "any": "Any",
  "food_refill_note": "Maximum food placed at once: 297 items. Refill may be needed.",
  "homeland_goals": "Homeland Goals",
  "workers_production": "Workers & Production",
  "options_on": "options on",
  "crop_work": "Crop work",
  "powered_facilities": "Powered facilities",
  "family": "Family",
  "power_preview_hint": "The facilities have to be in E-Mode (Power icon) to use electricity, facilities draw power when in range of a Crackle pole/generator, in E-Mode AND recipe selected, even if they are currently not crafting anything."
};
const GAME_TERMS={"GAME000TOKEN": "Tidewhisper Sandcastle", "GAME001TOKEN": "Harvest Moon Festival", "GAME002TOKEN": "Plant Research Module", "GAME003TOKEN": "Phonolfactory Table", "GAME004TOKEN": "Moonray Wheat Coins", "GAME005TOKEN": "Crackle Power Pole", "GAME006TOKEN": "Waxing Moon Pepper", "GAME007TOKEN": "Dance Pad Polisher", "GAME008TOKEN": "Moonray Wheat Coin", "GAME009TOKEN": "Woodworking Bench", "GAME010TOKEN": "Crackle Generator", "GAME011TOKEN": "Claw Game Cooker", "GAME012TOKEN": "Starfall Hammock", "GAME013TOKEN": "Floral Windmill", "GAME014TOKEN": "Furniture Store", "GAME015TOKEN": "Bouncy Brew Keg", "GAME016TOKEN": "Crafting Table", "GAME017TOKEN": "Moondew Radish", "GAME018TOKEN": "Waxing Moondew", "GAME019TOKEN": "Joy Wheel Loom", "GAME020TOKEN": "Aniipod Maker", "GAME021TOKEN": "Jukebox Dryer", "GAME022TOKEN": "Blazing Stove", "GAME023TOKEN": "Simmering Pot", "GAME024TOKEN": "Moonray Wheat", "GAME025TOKEN": "Carousel Mill", "GAME026TOKEN": "Harvest Moon", "GAME027TOKEN": "Dream Sparks", "GAME028TOKEN": "Storage Unit", "GAME029TOKEN": "Season Index", "GAME030TOKEN": "Chimney Kiln", "GAME031TOKEN": "Heat Furnace", "GAME032TOKEN": "Market Stall", "GAME033TOKEN": "Cooling Unit", "GAME034TOKEN": "Pickling Jar", "GAME035TOKEN": "Dream Spark", "GAME036TOKEN": "Co-op Store", "GAME037TOKEN": "Hatchinator", "GAME038TOKEN": "Crystalline", "GAME039TOKEN": "Artisanship", "GAME040TOKEN": "Instinctive", "GAME041TOKEN": "Nimbus Bed", "GAME042TOKEN": "Collection", "GAME043TOKEN": "Dewy House", "GAME044TOKEN": "Home Coins", "GAME045TOKEN": "Practical", "GAME046TOKEN": "Farmlands", "GAME047TOKEN": "Tenacious", "GAME048TOKEN": "Lightning", "GAME049TOKEN": "Legendary", "GAME050TOKEN": "Home Coin", "GAME051TOKEN": "Energetic", "GAME052TOKEN": "Judicious", "GAME053TOKEN": "Perfumery", "GAME054TOKEN": "Fireworks", "GAME055TOKEN": "Aniipods", "GAME056TOKEN": "Starfall", "GAME057TOKEN": "Colorful", "GAME058TOKEN": "Woodland", "GAME059TOKEN": "Farmland", "GAME060TOKEN": "Faithful", "GAME061TOKEN": "Prismana", "GAME062TOKEN": "Playful", "GAME063TOKEN": "Leisure", "GAME064TOKEN": "AniiEXP", "GAME065TOKEN": "Hauling", "GAME066TOKEN": "Flicker", "GAME067TOKEN": "Sunlamp", "GAME068TOKEN": "Moondew", "GAME069TOKEN": "Shining", "GAME070TOKEN": "Nimble", "GAME071TOKEN": "Laurel", "GAME072TOKEN": "Index", "GAME073TOKEN": "Water", "GAME074TOKEN": "Light", "GAME075TOKEN": "Giant", "GAME076TOKEN": "Grass", "GAME077TOKEN": "Earth", "GAME078TOKEN": "Wind", "GAME079TOKEN": "Well", "GAME080TOKEN": "Fire", "GAME081TOKEN": "Mine", "GAME082TOKEN": "Dark", "GAME083TOKEN": "Ice", "GAME084TOKEN": "Advanced Gemstone Dust", "GAME085TOKEN": "Advanced Lemon Incense", "GAME086TOKEN": "Advanced Wind Chime", "GAME087TOKEN": "Agave", "GAME088TOKEN": "Agave Drink", "GAME089TOKEN": "Agave Syrup", "GAME090TOKEN": "Aniipod", "GAME091TOKEN": "Aniipod Mega", "GAME092TOKEN": "Aniipod Pro", "GAME093TOKEN": "Apple", "GAME094TOKEN": "Apple Candy", "GAME095TOKEN": "Apple Juice", "GAME096TOKEN": "Apple Tart", "GAME097TOKEN": "Aromathyst", "GAME098TOKEN": "Bailite", "GAME099TOKEN": "Baleetle", "GAME100TOKEN": "Bamboo", "GAME101TOKEN": "Bamboo Joss Stick", "GAME102TOKEN": "Bamboo Ware", "GAME103TOKEN": "Berry Chocolate Coconut Pudding", "GAME104TOKEN": "Besauce", "GAME105TOKEN": "Blazen", "GAME106TOKEN": "Bolty", "GAME107TOKEN": "Bonesky", "GAME108TOKEN": "Bouldus", "GAME109TOKEN": "Bouquet", "GAME110TOKEN": "Bread", "GAME111TOKEN": "Budclaw", "GAME112TOKEN": "Budsquire", "GAME113TOKEN": "Bulbly", "GAME114TOKEN": "Candied Orange Flower", "GAME115TOKEN": "Candied Strawberries", "GAME116TOKEN": "Caramel Nut Chips", "GAME117TOKEN": "Celestis", "GAME118TOKEN": "Cherry Blossom", "GAME119TOKEN": "Cherry Blossom Rice Ball", "GAME120TOKEN": "Cherry Incense", "GAME121TOKEN": "Chestnut", "GAME122TOKEN": "Chestnut Purée", "GAME123TOKEN": "Chirpi", "GAME124TOKEN": "Cider Vinegar", "GAME125TOKEN": "Clay", "GAME126TOKEN": "Coarse Sifted Ore", "GAME127TOKEN": "Cocoa", "GAME128TOKEN": "Cocoa Powder", "GAME129TOKEN": "Cocoa Spread", "GAME130TOKEN": "Coconut", "GAME131TOKEN": "Coconut Cocoa", "GAME132TOKEN": "Coconut Cookie", "GAME133TOKEN": "Coconut Cooler", "GAME134TOKEN": "Coconut Milk", "GAME135TOKEN": "Coconut Oil", "GAME136TOKEN": "Copper Ore", "GAME137TOKEN": "Cornet", "GAME138TOKEN": "Cotton", "GAME139TOKEN": "Cotton Fabric", "GAME140TOKEN": "Cotton Thread", "GAME141TOKEN": "Cozite", "GAME142TOKEN": "Crafting Module", "GAME143TOKEN": "Cranberry", "GAME144TOKEN": "Cranberry Chocolate", "GAME145TOKEN": "Cranberry Jam", "GAME146TOKEN": "Cranberry Juice", "GAME147TOKEN": "Creamy Potato Soup", "GAME148TOKEN": "Cubbo", "GAME149TOKEN": "Dazmand", "GAME150TOKEN": "Deep Rock Spring Water", "GAME151TOKEN": "Densified Timber Component", "GAME152TOKEN": "Dewy", "GAME153TOKEN": "Doll", "GAME154TOKEN": "Dream Catcher", "GAME155TOKEN": "Dreaple", "GAME156TOKEN": "Dried Apple Slices", "GAME157TOKEN": "Dried Bean Curd", "GAME158TOKEN": "Dried Cherry Blossom", "GAME159TOKEN": "Dried Cranberries", "GAME160TOKEN": "Dried Flowers", "GAME161TOKEN": "Dried Ginseng", "GAME162TOKEN": "Dried Grapes", "GAME163TOKEN": "Dried Lemon Slices", "GAME164TOKEN": "Dried Strawberries", "GAME165TOKEN": "Dye", "GAME166TOKEN": "Dyed Cotton Fabric", "GAME167TOKEN": "Ecological Module", "GAME168TOKEN": "Eklue", "GAME169TOKEN": "Eko", "GAME170TOKEN": "Emberpup", "GAME171TOKEN": "Erlath", "GAME172TOKEN": "Fahloo", "GAME173TOKEN": "Fenmane", "GAME174TOKEN": "Fenrier", "GAME175TOKEN": "Fentuft", "GAME176TOKEN": "Flamerion", "GAME177TOKEN": "Flameruff", "GAME178TOKEN": "Flower Bread", "GAME179TOKEN": "Flowers In A Bottle", "GAME180TOKEN": "Flutternym", "GAME181TOKEN": "Fragrancier", "GAME182TOKEN": "Fulmintis", "GAME183TOKEN": "Gem", "GAME184TOKEN": "Gemstone Dust", "GAME185TOKEN": "Geoclaw", "GAME186TOKEN": "Geodeback", "GAME187TOKEN": "Ginseng", "GAME188TOKEN": "Ginseng Chestnut Cake", "GAME189TOKEN": "Ginseng Porridge", "GAME190TOKEN": "Ginseng Powder", "GAME191TOKEN": "Ginseng Water", "GAME192TOKEN": "Glacy", "GAME193TOKEN": "Glynsera", "GAME194TOKEN": "Gracewing", "GAME195TOKEN": "Grape Candy", "GAME196TOKEN": "Grape Jam", "GAME197TOKEN": "Grape Juice", "GAME198TOKEN": "Grape Lemon Drink", "GAME199TOKEN": "Grapes", "GAME200TOKEN": "Grizbo", "GAME201TOKEN": "Growth Bud", "GAME202TOKEN": "Growth Flower", "GAME203TOKEN": "Growth Fruit", "GAME204TOKEN": "Harvest Platter", "GAME205TOKEN": "Helgon", "GAME206TOKEN": "Helios", "GAME207TOKEN": "Helmut", "GAME208TOKEN": "Helmwhelp", "GAME209TOKEN": "Herbal Ginseng Aroma", "GAME210TOKEN": "Hexxin", "GAME211TOKEN": "Hot Cocoa", "GAME212TOKEN": "Hummin", "GAME213TOKEN": "Ignitis", "GAME214TOKEN": "Infergon", "GAME215TOKEN": "Inferlupa", "GAME216TOKEN": "Iris", "GAME217TOKEN": "Irisal", "GAME218TOKEN": "Irisalis", "GAME219TOKEN": "Jawling", "GAME220TOKEN": "Jello", "GAME221TOKEN": "Kitchen Module", "GAME222TOKEN": "Laminated Beams", "GAME223TOKEN": "Lavazar", "GAME224TOKEN": "Lavender", "GAME225TOKEN": "Lavender Cookies", "GAME226TOKEN": "Lavender Incense", "GAME227TOKEN": "Lavender Powder", "GAME228TOKEN": "Lavender Sachet", "GAME229TOKEN": "Leafy", "GAME230TOKEN": "Lemon", "GAME231TOKEN": "Lemon Incense", "GAME232TOKEN": "Lotion", "GAME233TOKEN": "Luminelle", "GAME234TOKEN": "Lunara", "GAME235TOKEN": "Magmarex", "GAME236TOKEN": "Malt Sugar", "GAME237TOKEN": "Maple Candy Apple Jam", "GAME238TOKEN": "Maple Candy Roasted Potatoes", "GAME239TOKEN": "Maple Candy Star", "GAME240TOKEN": "Maple Sugar Chunk", "GAME241TOKEN": "Maple Syrup", "GAME242TOKEN": "Melloblum", "GAME243TOKEN": "Microcrystalline Ore Plate", "GAME244TOKEN": "Milled Rice", "GAME245TOKEN": "Mineral Sand", "GAME246TOKEN": "Minespine", "GAME247TOKEN": "Mixed Perfume", "GAME248TOKEN": "Moondew Radish Slices", "GAME249TOKEN": "Natural Mineral Spring Water", "GAME250TOKEN": "Natural Rubber", "GAME251TOKEN": "Nimbi", "GAME252TOKEN": "Nuts", "GAME253TOKEN": "Orange Flower", "GAME254TOKEN": "Orange Flower Dew", "GAME255TOKEN": "Orange Flower Incense", "GAME256TOKEN": "Palm Bark", "GAME257TOKEN": "Palm Rope", "GAME258TOKEN": "Panpanta", "GAME259TOKEN": "Pawney", "GAME260TOKEN": "Pearl", "GAME261TOKEN": "Pearl Necklace", "GAME262TOKEN": "Pebbling", "GAME263TOKEN": "Petals", "GAME264TOKEN": "Piopiota", "GAME265TOKEN": "Plain Fresh Water", "GAME266TOKEN": "Plain Rice Porridge", "GAME267TOKEN": "Pomawk", "GAME268TOKEN": "Pomegg", "GAME269TOKEN": "Popota", "GAME270TOKEN": "Porcelain", "GAME271TOKEN": "Potato", "GAME272TOKEN": "Potato Chips", "GAME273TOKEN": "Potato Kvass", "GAME274TOKEN": "Pottery", "GAME275TOKEN": "Pranky", "GAME276TOKEN": "Premium Berry Chocolate Coconut Pudding", "GAME277TOKEN": "Premium Bread", "GAME278TOKEN": "Premium Jello", "GAME279TOKEN": "Premium Mixed Perfume", "GAME280TOKEN": "Premium Potato Soup", "GAME281TOKEN": "Premium River Washed Stones", "GAME282TOKEN": "Premium Rose Freshener", "GAME283TOKEN": "Premium Salted Lemon", "GAME284TOKEN": "Premium Soap", "GAME285TOKEN": "Premium Sweet Rice Wine", "GAME286TOKEN": "Premium Wheat", "GAME287TOKEN": "Quartz Ore", "GAME288TOKEN": "Quick Aromathyst", "GAME289TOKEN": "Quick Bamboo", "GAME290TOKEN": "Quick Coconut", "GAME291TOKEN": "Quick Deep Rock Spring Water", "GAME292TOKEN": "Quick Fresh Water", "GAME293TOKEN": "Quick Lemon", "GAME294TOKEN": "Quick Maple Syrup", "GAME295TOKEN": "Quick Natural Mineral Spring Water", "GAME296TOKEN": "Quick Potato", "GAME297TOKEN": "Quick Rice", "GAME298TOKEN": "Quick Scales", "GAME299TOKEN": "Quick Sea Salt", "GAME300TOKEN": "Quick Strawberry", "GAME301TOKEN": "Quick Well Water", "GAME302TOKEN": "Quick Wheat", "GAME303TOKEN": "Quick Wool", "GAME304TOKEN": "Refined Flour", "GAME305TOKEN": "Refined Ore", "GAME306TOKEN": "Resource Detector", "GAME307TOKEN": "Rice", "GAME308TOKEN": "Rice Drink", "GAME309TOKEN": "Rice Vinegar", "GAME310TOKEN": "Rich Grape Compote", "GAME311TOKEN": "River Washed Stones", "GAME312TOKEN": "Roasted Soybeans", "GAME313TOKEN": "Roasted Waxing Moon Pepper", "GAME314TOKEN": "Rock", "GAME315TOKEN": "Rock Candy", "GAME316TOKEN": "Rookey", "GAME317TOKEN": "Rose", "GAME318TOKEN": "Rose Concentrate", "GAME319TOKEN": "Rose Freshener", "GAME320TOKEN": "Rose Incense", "GAME321TOKEN": "Rose Shortbread", "GAME322TOKEN": "Rough Lumber", "GAME323TOKEN": "Rubber Duck", "GAME324TOKEN": "Salted Cherry Blossom", "GAME325TOKEN": "Salted Lemon", "GAME326TOKEN": "Scales", "GAME327TOKEN": "Scorchhowl", "GAME328TOKEN": "Sea Salt", "GAME329TOKEN": "Sheldon", "GAME330TOKEN": "Shell", "GAME331TOKEN": "Shell Ornament", "GAME332TOKEN": "Shelly", "GAME333TOKEN": "Sherro", "GAME334TOKEN": "Shredded Coconut", "GAME335TOKEN": "Shrubclaw", "GAME336TOKEN": "Sintered Ore Brick", "GAME337TOKEN": "Skippy", "GAME338TOKEN": "Soap", "GAME339TOKEN": "Somniwing", "GAME340TOKEN": "Soy Sauce", "GAME341TOKEN": "Soy Sauce Fried Rice", "GAME342TOKEN": "Soy Sauce Tofu", "GAME343TOKEN": "Soybean", "GAME344TOKEN": "Sparkelf", "GAME345TOKEN": "Sparki", "GAME346TOKEN": "Squarrel", "GAME347TOKEN": "Squashel", "GAME348TOKEN": "Standard Planks", "GAME349TOKEN": "Star", "GAME350TOKEN": "Star Wish Lantern", "GAME351TOKEN": "Steamed Vermicelli Roll", "GAME352TOKEN": "Stellarys", "GAME353TOKEN": "Strawberry", "GAME354TOKEN": "Strawberry Candy", "GAME355TOKEN": "Strawberry Cream Puff", "GAME356TOKEN": "Strawberry Jam", "GAME357TOKEN": "Strawberry Juice", "GAME358TOKEN": "Sugar Roasted Chestnuts", "GAME359TOKEN": "Sugarcane", "GAME360TOKEN": "Sugarcane Juice", "GAME361TOKEN": "Susuta", "GAME362TOKEN": "Sweet Rice Drink", "GAME363TOKEN": "Tanghulu", "GAME364TOKEN": "Thornblade", "GAME365TOKEN": "Toasted Rice Green Tea", "GAME366TOKEN": "Tofu", "GAME367TOKEN": "Tromber", "GAME368TOKEN": "Tubster", "GAME369TOKEN": "Tuckin", "GAME370TOKEN": "Turbo", "GAME371TOKEN": "Umbral Hot Pot", "GAME372TOKEN": "Umbral Pickle", "GAME373TOKEN": "Umbral Sweet Spicy Sauce", "GAME374TOKEN": "Veilfloat", "GAME375TOKEN": "Waleetle", "GAME376TOKEN": "Walnut", "GAME377TOKEN": "Walnut Cake", "GAME378TOKEN": "Walnut Milk", "GAME379TOKEN": "Well Water", "GAME380TOKEN": "Wheat", "GAME381TOKEN": "Wheat Tea", "GAME382TOKEN": "Wheatmeal", "GAME383TOKEN": "Willow Wood", "GAME384TOKEN": "Wind Chime", "GAME385TOKEN": "Wisptis", "GAME386TOKEN": "Wood Block", "GAME387TOKEN": "Wood Blocks", "GAME388TOKEN": "Wood Sculpture", "GAME389TOKEN": "Wool", "GAME390TOKEN": "Wool Fabric", "GAME391TOKEN": "Woolen Yarn", "GAME392TOKEN": "Woven Toy"};
const aliases={'Home Coins':'Home Coin','Farmlands':'Farmland','Moonray Wheat Coins':'Moonray Wheat Coin','Dream Sparks':'Dream Spark'};
function resolveGame(text){return String(text??'').replace(/GAME\d{3}TOKEN/g,token=>{const name=GAME_TERMS[token]||token;return window.AniilandI18n?.gameT?.('auto',aliases[name]||name)??name;});}
function t(key){const locale=window.AniilandI18n?.getLanguage?.()||'en-US';return resolveGame(window.AniilandLocales?.[locale]?.v2?.[key]??EN[key]??key);}
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function html(key){return `<span data-i18n-ignore>${escape(t(key))}</span>`;}
window.AniilandV2Text={t,html,resolveGame,en:EN,gameTerms:GAME_TERMS};
})();
